/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package life.jugnu.learnkafka.ch03.customerSerializer;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Customer extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1646473802080771781L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Customer\",\"namespace\":\"life.jugnu.learnkafka.ch03.customerSerializer\",\"fields\":[{\"name\":\"customerID\",\"type\":\"int\"},{\"name\":\"customerName\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int customerID;
  @Deprecated public java.lang.CharSequence customerName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Customer() {}

  /**
   * All-args constructor.
   */
  public Customer(java.lang.Integer customerID, java.lang.CharSequence customerName) {
    this.customerID = customerID;
    this.customerName = customerName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return customerID;
    case 1: return customerName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: customerID = (java.lang.Integer)value$; break;
    case 1: customerName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'customerID' field.
   */
  public java.lang.Integer getCustomerID() {
    return customerID;
  }

  /**
   * Sets the value of the 'customerID' field.
   * @param value the value to set.
   */
  public void setCustomerID(java.lang.Integer value) {
    this.customerID = value;
  }

  /**
   * Gets the value of the 'customerName' field.
   */
  public java.lang.CharSequence getCustomerName() {
    return customerName;
  }

  /**
   * Sets the value of the 'customerName' field.
   * @param value the value to set.
   */
  public void setCustomerName(java.lang.CharSequence value) {
    this.customerName = value;
  }

  /**
   * Creates a new Customer RecordBuilder.
   * @return A new Customer RecordBuilder
   */
  public static life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder newBuilder() {
    return new life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder();
  }
  
  /**
   * Creates a new Customer RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Customer RecordBuilder
   */
  public static life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder newBuilder(life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder other) {
    return new life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder(other);
  }
  
  /**
   * Creates a new Customer RecordBuilder by copying an existing Customer instance.
   * @param other The existing instance to copy.
   * @return A new Customer RecordBuilder
   */
  public static life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder newBuilder(life.jugnu.learnkafka.ch03.customerSerializer.Customer other) {
    return new life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder(other);
  }
  
  /**
   * RecordBuilder for Customer instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Customer>
    implements org.apache.avro.data.RecordBuilder<Customer> {

    private int customerID;
    private java.lang.CharSequence customerName;

    /** Creates a new Builder */
    private Builder() {
      super(life.jugnu.learnkafka.ch03.customerSerializer.Customer.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.customerID)) {
        this.customerID = data().deepCopy(fields()[0].schema(), other.customerID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerName)) {
        this.customerName = data().deepCopy(fields()[1].schema(), other.customerName);
        fieldSetFlags()[1] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing Customer instance
     * @param other The existing instance to copy.
     */
    private Builder(life.jugnu.learnkafka.ch03.customerSerializer.Customer other) {
            super(life.jugnu.learnkafka.ch03.customerSerializer.Customer.SCHEMA$);
      if (isValidValue(fields()[0], other.customerID)) {
        this.customerID = data().deepCopy(fields()[0].schema(), other.customerID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerName)) {
        this.customerName = data().deepCopy(fields()[1].schema(), other.customerName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'customerID' field.
      * @return The value.
      */
    public java.lang.Integer getCustomerID() {
      return customerID;
    }

    /**
      * Sets the value of the 'customerID' field.
      * @param value The value of 'customerID'.
      * @return This builder.
      */
    public life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder setCustomerID(int value) {
      validate(fields()[0], value);
      this.customerID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'customerID' field has been set.
      * @return True if the 'customerID' field has been set, false otherwise.
      */
    public boolean hasCustomerID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'customerID' field.
      * @return This builder.
      */
    public life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder clearCustomerID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerName() {
      return customerName;
    }

    /**
      * Sets the value of the 'customerName' field.
      * @param value The value of 'customerName'.
      * @return This builder.
      */
    public life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder setCustomerName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.customerName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'customerName' field has been set.
      * @return True if the 'customerName' field has been set, false otherwise.
      */
    public boolean hasCustomerName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerName' field.
      * @return This builder.
      */
    public life.jugnu.learnkafka.ch03.customerSerializer.Customer.Builder clearCustomerName() {
      customerName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Customer build() {
      try {
        Customer record = new Customer();
        record.customerID = fieldSetFlags()[0] ? this.customerID : (java.lang.Integer) defaultValue(fields()[0]);
        record.customerName = fieldSetFlags()[1] ? this.customerName : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
